In [1]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
np.random.seed(100)

### Step 0 : Define the inputs

In [3]:
def initialize_input_matrices(m,n):
    X = np.random.rand(m*n).reshape([m,n])
    Y = np.random.randint(low=0,high=2,size=m,dtype='int')
    return X,Y

In [4]:
def step_0():
    print('Give the dimensions of the input matrix X.',end=" ")
    print('Random Numbers will filled in the matrix of dimension of your choice')
    l = [int(x) for x in input('Number of rows x Number of columns (mxn) ').split(' ')]
    X, Y = initialize_input_matrices(l[0],l[1])
    return X, Y

### Step 1 : Initialize the weights and biases with random values

In [5]:
def step_1(m,n):
    wh = np.random.rand(m*n).reshape([n,m])
    bh = np.random.rand(m)
    wout = np.random.rand(m)
    bout = np.random.rand(1)
    return wh,bh,wout,bout

### Step 2 : Calculate hidden layer input

In [6]:
def step_2(X,wh,bh):
    return np.dot(X,wh) + bh

### Step 3 : Perform non-linear transformation

In [7]:
def sigmoid(z):
    return 1/(1+np.exp(-z))

In [8]:
def derivative_sigmoid(z):
#     return sigmoid(z) * (1-sigmoid(z)) # This is the original derivative
    return z*(1-z)

In [9]:
def relu(z):
    return np.maximum(z,0)

In [10]:
def derivative_relu(z):
    return z * (1-z)

### Step 4 : Perform linear and non-linear transformation of hidden layer activation at output layer

In [11]:
def step_4(hiddenlayer_activations,wout,bout):
    temp = np.dot(hiddenlayer_activations, np.transpose(wout))+np.transpose(bout)
    return sigmoid(temp)

### Step 5 : Calculate gradient of Error(E) at output layer

In [12]:
def step_5(output,Y):
    return Y-output

### Step 6 : Compute slope at output and hidden layer

In [13]:
def step_6(output,hiddenlayer_activations):
    slope_output_layer = derivative_sigmoid(output)
    slope_hidden_layer = derivative_sigmoid(hiddenlayer_activations)
    return slope_output_layer, slope_hidden_layer

### Step 7 : Compute delta at output layer

In [14]:
def step_7(E, slope_output_layer, lr):
    return E * slope_output_layer * lr

### Step 8 : Calculate Error at hidden layer

In [15]:
def step_8(d_output,wout):
    return np.dot(d_output, np.transpose(wout))

### Step 9: Compute delta at hidden layer

In [16]:
def step_9(Error_at_hidden_layer, slope_hidden_layer):
    return np.dot(Error_at_hidden_layer,slope_hidden_layer)

### Step 10: Update weight at both output and hidden layer

In [17]:
def step_10(hiddenlayer_activations, d_output,lr,wout,wh,X,d_hiddenlayer):
    wout += np.dot(np.transpose(hiddenlayer_activations),d_output) * lr
    wh += np.dot(np.transpose(X),d_hiddenlayer)*lr
    return wout, wh

### Step 11: Update biases at both output and hidden layer

In [18]:
def step_11(bh,bout,d_hiddenlayer,d_output,lr):
    bout += np.sum(d_output,axis=0)*lr
    bh += np.sum(d_hiddenlayer,axis=0)*lr
    return bout,bh

### Combining all the steps

In [28]:
def main():
    lr = 0.1
    X, Y = step_0()
    wh, bh, wout, bout = step_1(X.shape[0],X.shape[1])
    hidden_layer_input = step_2(X,wh,bh)
    hiddenlayer_activations = sigmoid(hidden_layer_input)
    output = step_4(hiddenlayer_activations,wout,bout)
    E = step_5(output,Y)
    slope_output_layer, slope_hidden_layer = step_6(output, hiddenlayer_activations)
    d_output = step_7(E,slope_output_layer,lr)
    Error_at_hidden_layer = step_8(d_output,wout)
    d_hiddenlayer = step_9(Error_at_hidden_layer, slope_hidden_layer)
    wout, wh = step_10(hiddenlayer_activations,d_output,lr, wout,wh,X,d_hiddenlayer)
    bout,bh = step_11(bh,bout,d_hiddenlayer,d_output,lr)
    print('X')
    print(X)
    print("Y")
    print(Y)
    print('wh')
    print(wh)
    print('bh')
    print(bh)
    print('wout')
    print(wout)
    print('bout')
    print(bout)
    print('Error')
    print(E)
    print('hidden_layer_input')
    print(hidden_layer_input)
    print('hiddenlayer_activations')
    print(hiddenlayer_activations)
    print('output')
    print(output)
    print('Slope_output_layer')
    print(slope_output_layer)
    print('Slope_hidden_layer')
    print(slope_hidden_layer)
    print('Error_at_hidden_layer')
    print(Error_at_hidden_layer)
    print('d_hiddenlayer')
    print(d_hiddenlayer)

In [29]:
main()

Give the dimensions of the input matrix X. Random Numbers will filled in the matrix of dimension of your choice
Number of rows x Number of columns (mxn) 3 4
X
[[0.36074842 0.88001849 0.27454204 0.22458118]
 [0.81397318 0.05820075 0.73015342 0.03267909]
 [0.59998723 0.03054111 0.85960489 0.43977952]]
Y
[1 0 0]
wh
[[0.1603438  0.92325104 0.95334658]
 [0.21075889 0.36037527 0.54925085]
 [0.27141184 0.46034817 0.69595135]
 [0.50020082 0.71597557 0.52587611]]
bh
[0.00072272 0.39427774 0.49181674]
wout
[0.40152795 0.3524513  0.49869426]
bout
[0.44297097]
Error
[ 0.19967568 -0.80292389 -0.8077868 ]
hidden_layer_input
[[0.43205179 1.33238977 1.62886438]
 [0.35934928 1.52709517 1.82579754]
 [0.55800062 1.67064619 1.91079176]]
hiddenlayer_activations
[[0.60636351 0.79123566 0.83601401]
 [0.5888829  0.82158091 0.86126033]
 [0.6359898  0.84166196 0.87110807]]
output
[0.80032432 0.80292389 0.8077868 ]
Slope_output_layer
[0.1598053  0.15823712 0.15526729]
Slope_hidden_layer
[[0.2386868  0.16518179 0

In [30]:
def with_epochs(num_epochs):
    lr = 0.1
    X, Y = step_0()
    wh, bh, wout, bout = step_1(X.shape[0],X.shape[1])
    
    for i in range(num_epochs):
        hidden_layer_input = step_2(X,wh,bh)
        hiddenlayer_activations = sigmoid(hidden_layer_input)
        output = step_4(hiddenlayer_activations,wout,bout)
        E = step_5(output,Y)

        
        slope_output_layer, slope_hidden_layer = step_6(output, hiddenlayer_activations)
        d_output = step_7(E,slope_output_layer,lr)
        Error_at_hidden_layer = step_8(d_output,wout)
        d_hiddenlayer = step_9(Error_at_hidden_layer, slope_hidden_layer)
        wout, wh = step_10(hiddenlayer_activations,d_output,lr, wout,wh,X,d_hiddenlayer)
        bout,bh = step_11(bh,bout,d_hiddenlayer,d_output,lr)
    
    print('After ' + str(i) + ' number of epochs')
    print('wh')
    print(wh)
    print('bh')
    print(bh)
    print('wout')
    print(wout)
    print('bout')
    print(bout)
    print('Error')
    print(E)
    print('hidden_layer_input')
    print(hidden_layer_input)
    print('hiddenlayer_activations')
    print(hiddenlayer_activations)
    print('output')
    print(output)
    print('Slope_output_layer')
    print(slope_output_layer)
    print('Slope_hidden_layer')
    print(slope_hidden_layer)
    print('Error_at_hidden_layer')
    print(Error_at_hidden_layer)
    print('d_hiddenlayer')
    print(d_hiddenlayer)

In [31]:
with_epochs(5)

Give the dimensions of the input matrix X. Random Numbers will filled in the matrix of dimension of your choice
Number of rows x Number of columns (mxn) 3 4
After 4 number of epochs
wh
[[0.49745415 0.66603194 0.23273927]
 [0.54928059 0.98773406 0.05353364]
 [0.61596404 0.11025989 0.46115187]
 [0.73407413 0.33440243 0.54489917]]
bh
[0.95092859 0.11093673 0.97998023]
wout
[0.73563269 0.8422353  0.72596636]
bout
[0.25462601]
Error
[ 0.11810617 -0.89380556 -0.90839711]
hidden_layer_input
[[1.74739451 0.55541514 1.46604144]
 [2.21309987 0.81411613 1.8138877 ]
 [2.54649162 1.98868237 1.67808475]]
hiddenlayer_activations
[[0.85162387 0.63539103 0.81245496]
 [0.90141973 0.69298593 0.85983108]
 [0.92733746 0.87960367 0.84265075]]
output
[0.88189383 0.89380556 0.90839711]
Slope_output_layer
[0.10415711 0.09491718 0.0832118 ]
Slope_hidden_layer
[[0.12636065 0.23166927 0.1523719 ]
 [0.0888622  0.21275643 0.12052159]
 [0.06738269 0.10590105 0.13259046]]
Error_at_hidden_layer
-0.011745765857916897
d