In [1]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
np.random.seed(100)

### Step 0 : Define the inputs

In [3]:
def initialize_input_matrices(m,n):
    X = np.random.rand(m*n).reshape([m,n])
    Y = np.random.randint(low=0,high=2,size=m,dtype='int')
    return X,Y

In [4]:
def step_0():
    print('Give the dimensions of the input matrix X.',end=" ")
    print('Random Numbers will filled in the matrix of dimension of your choice')
    l = [int(x) for x in input('Number of rows x Number of columns (mxn) ').split(' ')]
    X, Y = initialize_input_matrices(l[0],l[1])
    return X, Y

### Step 1 : Initialize the weights and biases with random values

In [5]:
def step_1(m,n):
    wh = np.random.rand(m*n).reshape([n,m])
    bh = np.random.rand(m)
    wout = np.random.rand(m)
    bout = np.random.rand(1)
    return wh,bh,wout,bout

### Step 2 : Calculate hidden layer input

In [6]:
def step_2(X,wh,bh):
    return np.dot(X,wh) + bh

### Step 3 : Perform non-linear transformation

In [7]:
def sigmoid(z):
    return 1/(1+np.exp(-z))

In [8]:
def derivative_sigmoid(z):
#     return sigmoid(z) * (1-sigmoid(z)) # This is the original derivative
    return z*(1-z)

In [9]:
def relu(z):
    return np.maximum(z,0)

In [10]:
def derivative_relu(z):
    return z * (1-z)

### Step 4 : Perform linear and non-linear transformation of hidden layer activation at output layer

In [11]:
def step_4(hiddenlayer_activations,wout,bout):
    temp = np.dot(hiddenlayer_activations, np.transpose(wout))+np.transpose(bout)
    return sigmoid(temp)

### Step 5 : Calculate gradient of Error(E) at output layer

In [12]:
def step_5(output,Y):
    return Y-output

### Step 6 : Compute slope at output and hidden layer

In [13]:
def step_6(output,hiddenlayer_activations):
    slope_output_layer = derivative_sigmoid(output)
    slope_hidden_layer = derivative_sigmoid(hiddenlayer_activations)
    return slope_output_layer, slope_hidden_layer

### Step 7 : Compute delta at output layer

In [14]:
def step_7(E, slope_output_layer, lr):
    return E * slope_output_layer * lr

### Step 8 : Calculate Error at hidden layer

In [15]:
def step_8(d_output,wout):
    return np.dot(d_output, np.transpose(wout))

### Step 9: Compute delta at hidden layer

In [16]:
def step_9(Error_at_hidden_layer, slope_hidden_layer):
    return np.dot(Error_at_hidden_layer,slope_hidden_layer)

### Step 10: Update weight at both output and hidden layer

In [17]:
def step_10(hiddenlayer_activations, d_output,lr,wout,wh,X,d_hiddenlayer):
    wout += np.dot(np.transpose(hiddenlayer_activations),d_output) * lr
    wh += np.dot(np.transpose(X),d_hiddenlayer)*lr
    return wout, wh

### Step 11: Update biases at both output and hidden layer

In [18]:
def step_11(bh,bout,d_hiddenlayer,d_output,lr):
    bout += np.sum(d_output,axis=0)*lr
    bh += np.sum(d_hiddenlayer,axis=0)*lr
    return bout,bh

### Combining all the steps

In [26]:
def main():
    lr = 0.1
    X, Y = step_0()
    wh, bh, wout, bout = step_1(X.shape[0],X.shape[1])
    hidden_layer_input = step_2(X,wh,bh)
    hiddenlayer_activations = sigmoid(hidden_layer_input)
    output = step_4(hiddenlayer_activations,wout,bout)
    E = step_5(output,Y)
    slope_output_layer, slope_hidden_layer = step_6(output, hiddenlayer_activations)
    d_output = step_7(E,slope_output_layer,lr)
    Error_at_hidden_layer = step_8(d_output,wout)
    d_hiddenlayer = step_9(Error_at_hidden_layer, slope_hidden_layer)
    wout, wh = step_10(hiddenlayer_activations,d_output,lr, wout,wh,X,d_hiddenlayer)
    bout,bh = step_11(bh,bout,d_hiddenlayer,d_output,lr)
    print('wh')
    print(wh)
    print('bh')
    print(bh)
    print('wout')
    print(wout)
    print('bout')
    print(bout)
    print('Error')
    print(E)

In [27]:
main()

Give the dimensions of the input matrix X. Random Numbers will filled in the matrix of dimension of your choice
Number of rows x Number of columns (mxn) 3 4
wh
[[0.95671663 0.17558474 0.11818244]
 [0.8627734  0.07461433 0.82499155]
 [0.8360824  0.07533068 0.01135555]
 [0.04828506 0.3569189  0.6656136 ]]
bh
[0.01109074 0.10750719 0.90079875]
wout
[0.79437494 0.8110745  0.63977609]
bout
[0.62408049]
Error
[ 0.0947468  -0.89509602  0.08093376]


In [28]:
def with_epochs(num_epochs):
    lr = 0.1
    X, Y = step_0()
    wh, bh, wout, bout = step_1(X.shape[0],X.shape[1])
    
    for i in range(num_epochs):
        hidden_layer_input = step_2(X,wh,bh)
        hiddenlayer_activations = sigmoid(hidden_layer_input)
        output = step_4(hiddenlayer_activations,wout,bout)
        E = step_5(output,Y)

        
        slope_output_layer, slope_hidden_layer = step_6(output, hiddenlayer_activations)
        d_output = step_7(E,slope_output_layer,lr)
        Error_at_hidden_layer = step_8(d_output,wout)
        d_hiddenlayer = step_9(Error_at_hidden_layer, slope_hidden_layer)
        wout, wh = step_10(hiddenlayer_activations,d_output,lr, wout,wh,X,d_hiddenlayer)
        bout,bh = step_11(bh,bout,d_hiddenlayer,d_output,lr)
    
    print('After ' + str(i) + ' number of epochs')
    print('wh')
    print(wh)
    print('bh')
    print(bh)
    print('wout')
    print(wout)
    print('bout')
    print(bout)
    print('Error')
    print(E)

In [ ]:
with_epochs(5)

Give the dimensions of the input matrix X. Random Numbers will filled in the matrix of dimension of your choice
